# Alpha 是內測階段，當features/* 或是 bugfix/*分支，使用pull request 方式合到release/*時，打包Alpha進行部署並通知QAteam測試
name: Alpha # 工作流程的名稱

on: # 觸發條件
  pull_request: # 當有 pull_request 事件時觸發
    branches: # 僅針對特定分支
      - releases/**
    types:
      - closed # PR 關閉才會執行

jobs:
  version: # 工作名稱
    uses: kwlai0927/workflows/.github/workflows/tag-alpha.yaml@main
    permissions:
      contents: write
    secrets: inherit

  build-and-push:
    needs: version
    runs-on: ubuntu-latest
    environment:
      name: alpha
      url: https://github.com
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build and Push to ECR
        uses: kwlai0927/action-ecr-push@main
        with:
          role-to-assume: ${{ secrets.AWS_NONPROD_ARTIFACT_ROLE_ARN }}
          ecr-repository: ${{ github.repository }}
          image-tag: ${{ needs.version.outputs.version }}

  helm:
    needs:
      - version
      - build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.DISPATCH_NONPROD_DEPLOYMENT_TOKEN }}
          repository: kwlai0927/nonprod-deployment
          event-type: kwlai0927/srv-chart
          client-payload: |
            {
              "repository": "${{ github.repository }}",
              "image-tag": "${{ needs.version.outputs.version }}",
              "environment": "alpha",
              "namespace": "llm"
            }